# Generated by Django 4.1.5 on 2023-01-13 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webside_side.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(choices=[('Dealer', 'Dealer'), ('Seller', 'Seller')], default='Seller', max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(default='New York, NY, United States', max_length=255)),
                ('make', models.CharField(max_length=33)),
                ('year', models.IntegerField()),
                ('bodytype', models.CharField(choices=[('Sedan', 'Sedan'), ('Classic', 'Classic'), ('Sport', 'Sport'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('SUV', 'SUV'), ('Mini Van', 'Mini Van'), ('Pickup Truck', 'Pickup Truck')], max_length=15)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10)),
                ('itemStatus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Sold', 'Sold')], max_length=8)),
                ('fuelType', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Petrol', 'Petrol')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miles', models.DecimalField(decimal_places=0, max_digits=10)),
                ('color', models.CharField(default='Blue', max_length=15)),
                ('engine', models.IntegerField()),
                ('description', models.TextField()),
                ('alloyWheels', models.BooleanField(default=True)),
                ('air', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('abs', models.BooleanField(default=False)),
                ('featured', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('powerLocks', models.BooleanField(default=False)),
                ('powerWindows', models.BooleanField(default=False)),
                ('cd', models.BooleanField(default=False)),
                ('bonnet', models.BooleanField(default=False)),
                ('airBags', models.BooleanField(default=False)),
                ('coolBox', models.BooleanField(default=False)),
                ('powerSteering', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=15)),
                ('image1', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=webside_side.models.photo_path)),
                ('image2', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=webside_side.models.photo_path)),
                ('image3', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=webside_side.models.photo_path)),
                ('image4', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=webside_side.models.photo_path)),
                ('image5', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=webside_side.models.photo_path)),
                ('bio', models.CharField(choices=[('Dealer', 'Dealer'), ('Seller', 'Seller')], default='Dealer', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
