# Generated by Django 4.1.5 on 2023-01-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webside_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(default='CARRRRRR', max_length=255)),
            ],
        ),
    ]
