# Generated by Django 4.1.5 on 2023-01-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webside_side', '0002_plm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plm',
            new_name='WebSiteName',
        ),
    ]
